name: CI
on:
  push:
    branches:
      - develop

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install --force && npm install -g @lhci/cli@0.13.x --force
      - run: npm run build
      - run: lhci autorun
